/**
 * Generated by anjay_codegen.py on 2021-08-24 13:22:53
 *
 * LwM2M Object: Anomaly detector
 * ID: 33651, URN: urn:oma:lwm2m:ext:33651, Optional, Single
 *
 * This object is used to report the anomaly detected by the ML-based
 * algorithms and to count the number of times it has been detected.
 */
#include <assert.h>
#include <stdbool.h>

#include <anjay/anjay.h>
#include <avsystem/commons/avs_defs.h>
#include <avsystem/commons/avs_memory.h>

#include <logging/log.h>
#include <zephyr.h>

#include "../processing.h"
#include "../utils.h"
#include "objects.h"

/**
 * Anomaly State: R, Single, Mandatory
 * type: boolean, range: N/A, unit: N/A
 * The current state of a detector.
 */
#define RID_ANOMALY_STATE 2000

/**
 * Anomaly Counter: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * The cumulative value of anomalies detected.
 */
#define RID_ANOMALY_COUNTER 2001

/**
 * Anomaly Treshold: RW, Single, Optional
 * type: float, range: N/A, unit: N/A
 * Input data is treated as anomaly if anomaly score is higher that
 * threshold value.
 */
#define RID_ANOMALY_TRESHOLD 2002

typedef struct anomaly_detector_object_struct {
    const anjay_dm_object_def_t *def;

    float anomaly_score;

    float anomaly_treshold;

    struct k_mutex instance_state_mtx;

    bool detector_state;
    int32_t detector_counter;
} anomaly_detector_object_t;


#define ANOMALY_TRESHOLD_INIT 0.3f

static inline anomaly_detector_object_t *
get_obj(const anjay_dm_object_def_t *const *obj_ptr) {
    assert(obj_ptr);
    return AVS_CONTAINER_OF(obj_ptr, anomaly_detector_object_t, def);
}

static int instance_reset(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid) {
    (void) anjay;

    anomaly_detector_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    assert(iid == 0);

    return 0;
}

static int list_resources(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid,
                          anjay_dm_resource_list_ctx_t *ctx) {
    (void) anjay;
    (void) obj_ptr;
    (void) iid;

    anjay_dm_emit_res(ctx, RID_ANOMALY_STATE,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_ANOMALY_COUNTER,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_ANOMALY_TRESHOLD,
                      ANJAY_DM_RES_RW, ANJAY_DM_RES_PRESENT);
    return 0;
}

static int resource_read(anjay_t *anjay,
                         const anjay_dm_object_def_t *const *obj_ptr,
                         anjay_iid_t iid,
                         anjay_rid_t rid,
                         anjay_riid_t riid,
                         anjay_output_ctx_t *ctx) {
    (void) anjay;

    anomaly_detector_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    assert(iid == 0);

    switch (rid) {
    case RID_ANOMALY_STATE:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_bool(ctx, obj->detector_state);

    case RID_ANOMALY_COUNTER:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, obj->detector_counter);

    case RID_ANOMALY_TRESHOLD:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_float(ctx, obj->anomaly_treshold);

    default:
        return ANJAY_ERR_METHOD_NOT_ALLOWED;
    }
}

static int resource_write(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid,
                          anjay_rid_t rid,
                          anjay_riid_t riid,
                          anjay_input_ctx_t *ctx) {
    (void) anjay;

    anomaly_detector_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    assert(iid == 0);

    switch (rid) {
    case RID_ANOMALY_TRESHOLD: {
        assert(riid == ANJAY_ID_INVALID);

        return anjay_get_float(ctx, &obj->anomaly_treshold);
    }

    default:
        return ANJAY_ERR_METHOD_NOT_ALLOWED;
    }
}

static const anjay_dm_object_def_t OBJ_DEF = {
    .oid = 33651,
    .handlers = {
        .list_instances = anjay_dm_list_instances_SINGLE,
        .instance_reset = instance_reset,

        .list_resources = list_resources,
        .resource_read = resource_read,
        .resource_write = resource_write,

        .transaction_begin = anjay_dm_transaction_NOOP,
        .transaction_validate = anjay_dm_transaction_NOOP,
        .transaction_commit = anjay_dm_transaction_NOOP,
        .transaction_rollback = anjay_dm_transaction_NOOP
    }
};

const anjay_dm_object_def_t **anomaly_detector_object_create(void) {
    anomaly_detector_object_t *obj = (anomaly_detector_object_t *) avs_calloc(1, sizeof(anomaly_detector_object_t));
    if (!obj) {
        return NULL;
    }
    obj->def = &OBJ_DEF;

    k_mutex_init(&obj->instance_state_mtx);

    obj->anomaly_treshold = ANOMALY_TRESHOLD_INIT;

    k_mutex_init(&obj->instance_state_mtx);

    return &obj->def;
}

void anomaly_detector_object_release(const anjay_dm_object_def_t **def) {
    if (def) {
        anomaly_detector_object_t *obj = get_obj(def);

        avs_free(obj);
    }
}

void anomaly_detector_object_update(anjay_t *anjay,
                                    const anjay_dm_object_def_t *const *def, float anomaly_score) {
    if (!anjay || !def) {
        return;
    }

    anomaly_detector_object_t *obj = get_obj(def);

    SYNCHRONIZED(obj->instance_state_mtx) {

        obj->anomaly_score = anomaly_score;

        if (anomaly_score > obj->anomaly_treshold){
            obj->detector_counter++;
            obj->detector_state = true;
            anjay_notify_changed(anjay, obj->def->oid, 0,
                                     RID_ANOMALY_COUNTER);
        } else {
            obj->detector_state = false;
        }

        anjay_notify_changed(anjay, obj->def->oid, 0,
                                     RID_ANOMALY_STATE);
    }
}
