/**
 * Generated by anjay_codegen.py on 2021-08-24 13:23:11
 *
 * LwM2M Object: ML Model
 * ID: 33654, URN: urn:oma:lwm2m:ext:33654, Optional, Single
 *
 * This object is used to report the meta information of the ML model
 * used by the device.
 */
#include <assert.h>
#include <stdbool.h>

#include <anjay/anjay.h>
#include <avsystem/commons/avs_defs.h>
#include <avsystem/commons/avs_memory.h>

#include "../processing.h"
#include "objects.h"

/**
 * Model Name: R, Single, Optional
 * type: string, range: N/A, unit: N/A
 * ML model name.
 */
#define RID_MODEL_NAME 2000

/**
 * Model version: R, Single, Optional
 * type: integer, range: N/A, unit: N/A
 * ML model version.
 */
#define RID_MODEL_VERSION 2001

typedef struct ml_model_object_struct {
    const anjay_dm_object_def_t *def;

} ml_model_object_t;

static inline ml_model_object_t *
get_obj(const anjay_dm_object_def_t *const *obj_ptr) {
    assert(obj_ptr);
    return AVS_CONTAINER_OF(obj_ptr, ml_model_object_t, def);
}

static int list_resources(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid,
                          anjay_dm_resource_list_ctx_t *ctx) {
    (void) anjay;
    (void) obj_ptr;
    (void) iid;

    anjay_dm_emit_res(ctx, RID_MODEL_NAME,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_MODEL_VERSION,
                      ANJAY_DM_RES_R, ANJAY_DM_RES_PRESENT);
    return 0;
}

static int resource_read(anjay_t *anjay,
                         const anjay_dm_object_def_t *const *obj_ptr,
                         anjay_iid_t iid,
                         anjay_rid_t rid,
                         anjay_riid_t riid,
                         anjay_output_ctx_t *ctx) {
    (void) anjay;

    ml_model_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    assert(iid == 0);

    switch (rid) {
    //TODO Wrapper should be extended to provide Model Name and Version.
    case RID_MODEL_NAME:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_string(ctx, "FogML Model");

    //TODO In the next specification should be changed to string.
    case RID_MODEL_VERSION:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, FOGML_MODEL_VERSION);

    default:
        return ANJAY_ERR_METHOD_NOT_ALLOWED;
    }
}

static const anjay_dm_object_def_t OBJ_DEF = {
    .oid = 33654,
    .handlers = {
        .list_instances = anjay_dm_list_instances_SINGLE,

        .list_resources = list_resources,
        .resource_read = resource_read,

        .transaction_begin = anjay_dm_transaction_NOOP,
        .transaction_validate = anjay_dm_transaction_NOOP,
        .transaction_commit = anjay_dm_transaction_NOOP,
        .transaction_rollback = anjay_dm_transaction_NOOP
    }
};

const anjay_dm_object_def_t **ml_model_object_create(void) {
    ml_model_object_t *obj = (ml_model_object_t *) avs_calloc(1, sizeof(ml_model_object_t));
    if (!obj) {
        return NULL;
    }
    obj->def = &OBJ_DEF;

    return &obj->def;
}

void ml_model_object_release(const anjay_dm_object_def_t **def) {
    if (def) {
        ml_model_object_t *obj = get_obj(def);

        avs_free(obj);
    }
}
