/**
 * Generated by anjay_codegen.py on 2021-08-02 12:50:18
 *
 * LwM2M Object: Pattern detector
 * ID: 33650, URN: urn:oma:lwm2m:ext:33650, Optional, Multiple
 *
 * This object is used to report the pattern detected by the ML-based
 * classification algorithms and to count the number of times it has been
 * detected.
 */
#include <assert.h>
#include <stdbool.h>

#include <anjay/anjay.h>
#include <avsystem/commons/avs_defs.h>
#include <avsystem/commons/avs_list.h>
#include <avsystem/commons/avs_memory.h>

#include <drivers/sensor.h>
#include <logging/log.h>
#include <zephyr.h>

#include "../processing.h"
#include "../utils.h"
#include "objects.h"

LOG_MODULE_REGISTER(pattern_detector);

/**
 * Detector State: R, Single, Mandatory
 * type: boolean, range: N/A, unit: N/A
 * The current state of a detector.
 */
#define RID_DETECTOR_STATE 2000

/**
 * Detector Counter: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * The cumulative value of patterns detected.
 */
#define RID_DETECTOR_COUNTER 2001

/**
 * Pattern Name: R, Single, Mandatory
 * type: string, range: N/A, unit: N/A
 * Name of the pattern being detected.
 */
#define RID_PATTERN_NAME 2002

typedef struct pattern_detector_instance_state_struct {
    bool detector_state;
    int32_t detector_counter;
} pattern_detector_instance_state_t;

typedef struct pattern_detector_instance_struct {
    anjay_iid_t iid;

    pattern_detector_instance_state_t curr_state;
    const char *pattern_name;
} pattern_detector_instance_t;

typedef struct pattern_detector_object_struct {
    const anjay_dm_object_def_t *def;

    pattern_detector_instance_t *instances;
    struct k_mutex instance_state_mtx;

    int class_count;
    const char **class_labels;
} pattern_detector_object_t;

static const pattern_detector_instance_state_t INITIAL_STATE = {
    .detector_state = false,
    .detector_counter = 0
};

static pattern_detector_instance_t *
find_instance(const pattern_detector_object_t *obj, anjay_iid_t iid) {
    return iid < obj->class_count ? &obj->instances[iid] : NULL;
}

static inline pattern_detector_object_t *
get_obj(const anjay_dm_object_def_t *const *obj_ptr) {
    assert(obj_ptr);
    return AVS_CONTAINER_OF(obj_ptr, pattern_detector_object_t, def);
}

static int list_instances(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_dm_list_ctx_t *ctx) {
    (void) anjay;

    pattern_detector_object_t *obj = get_obj(obj_ptr);
    assert(obj);

    for (size_t i = 0; i < obj->class_count; i++) {
        anjay_dm_emit(ctx, i);
    }

    return 0;
}

static int init_instance(pattern_detector_instance_t *inst, anjay_iid_t iid, const char *label) {
    assert(iid != ANJAY_ID_INVALID);

    inst->iid = iid;
    inst->curr_state = INITIAL_STATE;
    inst->pattern_name = label;

    return 0;
}

static pattern_detector_instance_t *add_instance(pattern_detector_object_t *obj,
                                                 anjay_iid_t iid) {
    assert(iid < obj->class_count);
    pattern_detector_instance_t *created = &obj->instances[iid];
    return init_instance(created, iid, obj->class_labels[iid]) ? NULL : created;
}

static int list_resources(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid,
                          anjay_dm_resource_list_ctx_t *ctx) {
    (void) anjay;
    (void) obj_ptr;
    (void) iid;

    anjay_dm_emit_res(ctx, RID_DETECTOR_STATE, ANJAY_DM_RES_R,
                      ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_DETECTOR_COUNTER, ANJAY_DM_RES_R,
                      ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_PATTERN_NAME, ANJAY_DM_RES_R,
                      ANJAY_DM_RES_PRESENT);
    return 0;
}

static int resource_read(anjay_t *anjay,
                         const anjay_dm_object_def_t *const *obj_ptr,
                         anjay_iid_t iid,
                         anjay_rid_t rid,
                         anjay_riid_t riid,
                         anjay_output_ctx_t *ctx) {
    (void) anjay;

    pattern_detector_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    pattern_detector_instance_t *inst = find_instance(obj, iid);
    assert(inst);

    switch (rid) {
    case RID_DETECTOR_STATE:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_bool(ctx, inst->curr_state.detector_state);

    case RID_DETECTOR_COUNTER:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, inst->curr_state.detector_counter);

    case RID_PATTERN_NAME:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_string(ctx, inst->pattern_name);

    default:
        return ANJAY_ERR_METHOD_NOT_ALLOWED;
    }
}

static const anjay_dm_object_def_t OBJ_DEF = {
    .oid = 33650,
    .handlers = {
        .list_instances = list_instances,

        .list_resources = list_resources,
        .resource_read = resource_read,
    }
};

const anjay_dm_object_def_t **pattern_detector_object_create(int class_count, const char **class_labels) {

    pattern_detector_object_t *obj = (pattern_detector_object_t *) avs_calloc(
            1,
            sizeof(pattern_detector_object_t) + class_count * sizeof(float));
    if (!obj) {
        return NULL;
    }
    obj->def = &OBJ_DEF;

    obj->class_count = class_count;
    obj->class_labels = class_labels;

    obj->instances = (pattern_detector_instance_t *) avs_calloc(
            class_count, sizeof(pattern_detector_instance_t));
    if (!obj->instances) {
        pattern_detector_object_release(&obj->def);
        return NULL;
    }

    for (size_t i = 0; i < class_count; i++) {
        if (!add_instance(obj, i)) {
            pattern_detector_object_release(&obj->def);
            return NULL;
        }
    }
    k_mutex_init(&obj->instance_state_mtx);

    return &obj->def;
}

void pattern_detector_object_release(const anjay_dm_object_def_t **def) {
    if (def) {
        pattern_detector_object_t *obj = get_obj(def);
        avs_free(obj->instances);
        avs_free(obj);
    }
}

void pattern_detector_object_update_detected_class(anjay_t *anjay,
    const anjay_dm_object_def_t *const *def, int detected_class) {
    if (!anjay || !def) {
        return;
    }

    pattern_detector_object_t *obj = get_obj(def);

    SYNCHRONIZED(obj->instance_state_mtx) {
        LOG_INF("Classified: %s", obj->class_labels[detected_class]);
        for (size_t i = 0; i < obj->class_count; i++) {
            pattern_detector_instance_t *it = &obj->instances[i];

            if (it->iid == detected_class) {
                if (!it->curr_state.detector_state) {
                    it->curr_state.detector_state = true;
                    anjay_notify_changed(anjay, obj->def->oid, i,
                        RID_DETECTOR_STATE);
                }
                it->curr_state.detector_counter++;
                anjay_notify_changed(anjay, obj->def->oid, i,
                    RID_DETECTOR_COUNTER);
            } else {
                if (it->curr_state.detector_state) {
                    it->curr_state.detector_state = false;
                    anjay_notify_changed(anjay, obj->def->oid, i,
                        RID_DETECTOR_STATE);
                }
            }
        }
    }
}
